server:
  port: 8888

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB
  redis:
    port: 6379
    host: localhost
  application:
    name: xuexilema_blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_

qiniu:
  accessKey: OKilSqDrTyzLmqDYKNw1Xf13GUPNdi_V39ot3xyA
  accessSecretKey: -36cLs-6SEZc9sp7YzxbRgsgW6vQ7mN3_bJruTEJ


